### ISSUE TITLE
To Lazy to Write You an Email

### ISSUE THREAD

**Issue by dchemishanov** [Anarcroth/pyther#1]
I will be in Blago this weekend. If you agree on a beer, I will contribute to this project. :P

**Comment by Anarcroth** [comment]
I agree on two beers!

**Comment by dchemishanov** [comment]
It was so hard to convince me...

**Comment by Anarcroth** [comment]
@dchemishanov 1 pull request = 1 beer. On 5 PRs we bust out the tequila

**Comment by Anarcroth** [comment]
@dchemishanov ey don't make me come to sofia and drink another beer with you for that PR

**Comment by dchemishanov** [comment]
@Anarcroth You drunk only one beer, but I'll overlook the fact and will contribute the pr. However, give me a day to enjoy the company of the family labrador because she traveled a lot and we've just met 2000 km away from home.

**Comment by Anarcroth** [comment]
@dchemishanov haha I am just joking. Don't feel pressured to do anything :) have fun with the family
